apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: wordpress-site
spec:
  replicas: 3
  selector: 
     matchLabels:
       env: wp
  template:
    metadata:
      labels:
        env: wp
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.mysql-db.svc.cluster.local:3306
          envFrom:
            - secretRef:
                name: wp-secret
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
         
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: pvc-wordpress
      



