apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
  namespace: wordpress-site
spec:
  storageClassName: sc-wordpress
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
