apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress-site
type: Opaque
data:
  WORDPRESS_DB_USER: c2FsbGFt # base64 for sallam
  WORDPRESS_DB_PASSWORD: bXlzcWwtcGFzcw== # base64 for mysql-pass
  WORDPRESS_DB_NAME: d29yZHByZXNz # base64 for wordpress
   
