apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-my-sql
  namespace: mysql-db
spec:
  storageClassName: sc-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
