apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-db
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWwtcm9vdC1wYXNz # base64 for mysql-root-pass
  MYSQL_DATABASE: d29yZHByZXNz # base64 for  wordpress
  MYSQL_USER: c2FsbGFt # base64 for sallam
  MYSQL_PASSWORD: bXlzcWwtcGFzcw== # base64 for mysql-pass


