apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-db
spec:
  type: ClusterIP
  selector:
    env: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
